"""
MedBrief AI — AI Clinical Summary Schemas
Step 12: AI Clinical Summary + Evidence/Source Reference Layer

Defines strict Pydantic schemas for:
1. Gemini structured output generation
2. Evidence citations linking statements to source documents/pages
3. Grounded summary sections for QUICK_CLINICAL, DETAILED_CLINICAL, MEDICATION, and INVESTIGATION modes
4. Uncertainty and conflict tracking
"""

from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, ConfigDict


class SummaryType(str, Enum):
    QUICK_CLINICAL = "QUICK_CLINICAL"
    DETAILED_CLINICAL = "DETAILED_CLINICAL"
    MEDICATION = "MEDICATION"
    INVESTIGATION = "INVESTIGATION"


class SummaryStatus(str, Enum):
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    REVIEWED = "REVIEWED"
    APPROVED = "APPROVED"
    ARCHIVED = "ARCHIVED"


class SummaryEvidenceCitation(BaseModel):
    """
    Direct citation pointing to a verifiable patient document and page.
    Every factual claim generated by the clinical summarizer must resolve to genuine source evidence.
    """
    model_config = ConfigDict(from_attributes=True)

    document_id: Optional[str] = Field(
        default=None,
        description="UUID of the source document in the database.",
    )
    document_name: Optional[str] = Field(
        default=None,
        description="Human-readable filename of the source document.",
    )
    page_number: Optional[int] = Field(
        default=None,
        description="1-based page number where the clinical fact was documented.",
    )
    document_page_id: Optional[str] = Field(
        default=None,
        description="UUID of the specific document_page record if available.",
    )
    source_snippet: str = Field(
        ...,
        description="Exact or near-verbatim quote from the medical record supporting this claim.",
    )
    source_section: Optional[str] = Field(
        default=None,
        description="Document section where fact was located (e.g. 'Discharge Medications', 'History of Present Illness').",
    )


class SummaryStatement(BaseModel):
    """
    An atomic clinical assertion with source citations and uncertainty flags.
    """
    model_config = ConfigDict(from_attributes=True)

    statement: str = Field(
        ...,
        description="Verbatim or grounded clinical statement synthesized from the medical record.",
    )
    citations: List[SummaryEvidenceCitation] = Field(
        default_factory=list,
        description="List of document citations directly grounding this statement.",
    )
    is_uncertain: bool = Field(
        default=False,
        description="True if the documented fact has conflicting sources, is suspected, or lacks verifiable evidence.",
    )
    uncertainty_note: Optional[str] = Field(
        default=None,
        description="Explanation of why this fact is uncertain or conflicting (e.g. 'Documented as possible NSTEMI on 2026-02-14').",
    )


class StructuredSummarySection(BaseModel):
    """
    A logical section of the clinical summary (e.g., Active Diagnoses, Medications, Key Events).
    """
    model_config = ConfigDict(from_attributes=True)

    section_key: str = Field(
        ...,
        description="Unique programmatic identifier (e.g. 'overview', 'diagnoses', 'medications', 'investigations', 'outstanding_items').",
    )
    title: str = Field(
        ...,
        description="Human-readable section title (e.g. 'Current & Active Diagnoses', 'Medication Changes').",
    )
    summary_text: Optional[str] = Field(
        default=None,
        description="Optional narrative paragraph summarizing the section.",
    )
    bullet_points: List[SummaryStatement] = Field(
        default_factory=list,
        description="Grounded clinical bullet points with evidence citations.",
    )


class StructuredClinicalSummaryOutput(BaseModel):
    """
    Complete structured clinical summary output produced by Gemini and validated by Pydantic.
    """
    model_config = ConfigDict(from_attributes=True)

    patient_id: str = Field(
        ...,
        description="UUID of the patient.",
    )
    patient_name: Optional[str] = Field(
        default=None,
        description="Name of the patient.",
    )
    summary_type: str = Field(
        ...,
        description="Mode of summary (QUICK_CLINICAL, DETAILED_CLINICAL, MEDICATION, INVESTIGATION).",
    )
    title: str = Field(
        ...,
        description="Descriptive title of the summary.",
    )
    overview: str = Field(
        ...,
        description="High-level clinical overview synthesizing the patient's condition (1-2 paragraphs).",
    )
    sections: List[StructuredSummarySection] = Field(
        default_factory=list,
        description="Structured clinical sections composing the full summary.",
    )
    overall_evidence_count: int = Field(
        default=0,
        description="Total count of verifiable evidence citations in the summary.",
    )
    has_insufficient_data: bool = Field(
        default=False,
        description="True if the uploaded record did not contain enough clinical information to synthesize a full summary.",
    )
    generation_notes: Optional[str] = Field(
        default=None,
        description="Safety or provenance notes regarding the generation.",
    )


# ── REST API DTOs ─────────────────────────────────────────────────────────────

class SummaryGenerateRequest(BaseModel):
    summary_type: SummaryType = Field(
        default=SummaryType.QUICK_CLINICAL,
        description="Type/mode of clinical summary to generate.",
    )
    custom_instructions: Optional[str] = Field(
        default=None,
        max_length=500,
        description="Optional clinician instructions (e.g. 'Focus on cardiology discharge plan').",
    )


class EvidenceReferenceResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    patient_id: str
    document_id: str
    document_name: Optional[str] = None
    document_page_id: Optional[str] = None
    page_number: Optional[int] = None
    parent_entity_type: str
    parent_entity_id: str
    source_section: Optional[str] = None
    source_text: str
    source_type: str
    confidence: Optional[float] = 1.0
    created_at: str


class SummaryItemResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    patient_id: str
    summary_type: str
    summary_type_label: str
    title: str
    status: str
    is_ai_generated: bool
    model_name: Optional[str] = None
    model_version: Optional[str] = None
    evidence_count: int = 0
    created_at: str
    updated_at: str


class SummaryDetailResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    patient_id: str
    patient_name: str
    patient_mrn: str
    summary_type: str
    summary_type_label: str
    title: str
    overview: str
    structured_content: StructuredClinicalSummaryOutput
    evidence_references: List[EvidenceReferenceResponse]
    status: str
    is_ai_generated: bool
    model_name: Optional[str] = None
    model_version: Optional[str] = None
    created_at: str
    updated_at: str


class PatientSummariesListResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    patient_id: str
    patient_name: str
    patient_mrn: str
    items: List[SummaryItemResponse]
    total: int
    page: int
    page_size: int
    total_pages: int
